server:
  port: 8081

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: serviceShuffle
        uri: lb://service-Shuffle
        predicates:
        - Path=/service-Shuffle/**
        filters:
        - RewritePath=/shuffle/(?<segment>.*), /$\{segment}
        - name: Hystrix
          args:
            name: monitor-shuffle
            fallbackUri: forward:/fallback/service-Shuffle
      - id: serviceLog
        uri: lb://service-Log
        predicates:
        - Path=/service-Log/**
        filters:
        - RewritePath=/service-Log/(?<segment>.*), /$\{segment}
        - name: Hystrix
          args:
            name: monitor-log
            fallbackUri: forward:/fallback/service-Log  
    consul:
      discovery:
        instanceId: Gateway
        health-check-interval: 5s
      config:
        management: 
          enabled: true
management:
  security: 
    enabled: false
  endpoints:
    web:
      exposure:
        include: hystrix.stream, info, health
     