spring:
  cloud:
    consul:
      discovery:
        instanceId: ServiceA
        health-check-interval: 5s
      config:
        management: 
          enabled: true
management:
  security: 
    enabled: false
project:  
  cloud:  
    log:  
      uri:  log
      hostname: service-log