server:
  port: 8083

spring:
  cloud:
    consul:
      discovery:
        instanceId: ${spring.application.name}:${random.value}
        health-check-interval: 5s
      config:
        management: 
          enabled: true
management:
  security: 
    enabled: false